// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_averages
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class AverageConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Average>
    {
        public AverageConfiguration()
            : this("dbo")
        {
        }
 
        public AverageConfiguration(string schema)
        {
            ToTable(schema + ".hba_averages");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ScoreSheetId).HasColumnName("score_sheet_id").IsRequired().HasColumnType("int");
            Property(x => x.SeriesAverage).HasColumnName("series_average").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Scoresheet).WithMany(b => b.Averages).HasForeignKey(c => c.ScoreSheetId); // hba_averages_fk1
        }
    }

}
// </auto-generated>
