// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_averages
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Average: Entity<int>
    {
        public int Id { get; set; } // id (Primary key)
        public int ScoreSheetId { get; set; } // score_sheet_id
        public int SeriesAverage { get; set; } // series_average

        // Foreign keys
        public virtual Scoresheet Scoresheet { get; set; } // hba_averages_fk1
    }

}
// </auto-generated>
