// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_bowler_note
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class BowlernoteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Bowlernote>
    {
        public BowlernoteConfiguration()
            : this("dbo")
        {
        }
 
        public BowlernoteConfiguration(string schema)
        {
            ToTable(schema + ".hba_bowler_note");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.BowlerId).HasColumnName("bowler_id").IsRequired().HasColumnType("int");
            Property(x => x.Season).HasColumnName("season").IsRequired().HasColumnType("int");
            Property(x => x.Note).HasColumnName("note").IsRequired().HasColumnType("nvarchar");
            Property(x => x.Rank).HasColumnName("rank").IsOptional().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Bowler).WithMany(b => b.Bowlernotes).HasForeignKey(c => c.BowlerId); // hba_bowler_note_fk1
        }
    }

}
// </auto-generated>
