// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_bowler
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Bowler: Entity<int>
    {
        public int Id { get; set; } // id (Primary key)
        public string BowlerName { get; set; } // bowler_name (length: 30)
        public string Address { get; set; } // address (length: 255)
        public string Phone { get; set; } // phone (length: 50)
        public string PrivacyFlag { get; set; } // privacy_flag (length: 1)
        public string ActiveFlag { get; set; } // active_flag (length: 1)
        public string Gender { get; set; } // gender (length: 1)
        public int TeamId { get; set; } // team_id
        public int Position { get; set; } // position
        public string Email { get; set; } // email (length: 255)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Bowlernote> Bowlernotes { get; set; } // hba_bowler_note.hba_bowler_note_fk1
        public virtual System.Collections.Generic.ICollection<Scoresheet> Scoresheets { get; set; } // hba_score_sheet.hba_score_sheet_fk1

        // Foreign keys
        public virtual Team Team { get; set; } // hba_bowler_fk1
        
        public Bowler()
        {
            Bowlernotes = new System.Collections.Generic.List<Bowlernote>();
            Scoresheets = new System.Collections.Generic.List<Scoresheet>();
        }
    }

}
// </auto-generated>
