// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_draw
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Draw: Entity<int>
    {
        public int Id { get; set; } // id (Primary key)
        public int TeamId { get; set; } // team_id
        public int WeekId { get; set; } // week_id
        public int Lane { get; set; } // lane
        public int Pairing { get; set; } // pairing
        public int Game1 { get; set; } // game_1
        public int Game2 { get; set; } // game_2
        public int Game3 { get; set; } // game_3
        public int Series { get; set; } // series
        public int Bonus { get; set; } // bonus
        public int Total { get; set; } // total
        public string LegalLineup { get; set; } // legal_lineup (length: 1)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Scoresheet> Scoresheets { get; set; } // hba_score_sheet.hba_score_sheet_fk2

        // Foreign keys
        public virtual Team Team { get; set; } // hba_draw_fk2
        public virtual Week Week { get; set; } // hba_draw_fk1
        
        public Draw()
        {
            Scoresheets = new System.Collections.Generic.List<Scoresheet>();
        }
    }

}
// </auto-generated>
