// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class FakeMyDbContext : IMyDbContext
    {
        public System.Data.Entity.DbSet<Average> Averages { get; set; }
        public System.Data.Entity.DbSet<Bowler> Bowlers { get; set; }
        public System.Data.Entity.DbSet<Bowlernote> Bowlernotes { get; set; }
        public System.Data.Entity.DbSet<Draw> Draws { get; set; }
        public System.Data.Entity.DbSet<Scoresheet> Scoresheets { get; set; }
        public System.Data.Entity.DbSet<Team> Teams { get; set; }
        public System.Data.Entity.DbSet<Teamnote> Teamnotes { get; set; }
        public System.Data.Entity.DbSet<Vindividualgame> Vindividualgames { get; set; }
        public System.Data.Entity.DbSet<VRollingAverage> VRollingAverages { get; set; }
        public System.Data.Entity.DbSet<Vweek> Vweeks { get; set; }
        public System.Data.Entity.DbSet<Week> Weeks { get; set; }

        public FakeMyDbContext()
        {
            Averages = new FakeDbSet<Average>("Id");
            Bowlers = new FakeDbSet<Bowler>("Id");
            Bowlernotes = new FakeDbSet<Bowlernote>("Id");
            Draws = new FakeDbSet<Draw>("Id");
            Scoresheets = new FakeDbSet<Scoresheet>("Id");
            Teams = new FakeDbSet<Team>("Id");
            Teamnotes = new FakeDbSet<Teamnote>("Id");
            Vindividualgames = new FakeDbSet<Vindividualgame>("Season", "WeekNumber", "BowlerId", "Handicap", "Game", "Game1", "DrawId");
            VRollingAverages = new FakeDbSet<VRollingAverage>("Id");
            Vweeks = new FakeDbSet<Vweek>("Season", "WeekNumber", "Round", "Id");
            Weeks = new FakeDbSet<Week>("Id");
        }
        
        public int SaveChangesCount { get; private set; } 
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }
        
        public void Dispose()
        {
            Dispose(true);
        }
        
        // Stored Procedures
        public System.Collections.Generic.List<HbaSAveragesAuditReturnModel> HbaSAveragesAudit(int? pWeekId)
        {
            int procResult;
            return HbaSAveragesAudit(pWeekId, out procResult);
        }

        public System.Collections.Generic.List<HbaSAveragesAuditReturnModel> HbaSAveragesAudit(int? pWeekId, out int procResult)
        {

            procResult = 0;
            return new System.Collections.Generic.List<HbaSAveragesAuditReturnModel>();
        }

        public System.Collections.Generic.List<HbaSEoyCertificateReturnModel> HbaSEoyCertificate(int? pSeason)
        {
            int procResult;
            return HbaSEoyCertificate(pSeason, out procResult);
        }

        public System.Collections.Generic.List<HbaSEoyCertificateReturnModel> HbaSEoyCertificate(int? pSeason, out int procResult)
        {

            procResult = 0;
            return new System.Collections.Generic.List<HbaSEoyCertificateReturnModel>();
        }

        public System.Collections.Generic.List<HbaSRoundWeekIdsReturnModel> HbaSRoundWeekIds(int? pWeekId)
        {
            int procResult;
            return HbaSRoundWeekIds(pWeekId, out procResult);
        }

        public System.Collections.Generic.List<HbaSRoundWeekIdsReturnModel> HbaSRoundWeekIds(int? pWeekId, out int procResult)
        {

            procResult = 0;
            return new System.Collections.Generic.List<HbaSRoundWeekIdsReturnModel>();
        }

        public System.Collections.Generic.List<HbaSSeasonAttendanceReturnModel> HbaSSeasonAttendance(int? pSeason)
        {
            int procResult;
            return HbaSSeasonAttendance(pSeason, out procResult);
        }

        public System.Collections.Generic.List<HbaSSeasonAttendanceReturnModel> HbaSSeasonAttendance(int? pSeason, out int procResult)
        {

            procResult = 0;
            return new System.Collections.Generic.List<HbaSSeasonAttendanceReturnModel>();
        }

    }
}
// </auto-generated>
