// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class HbaSEoyCertificateReturnModel
    {
        public System.Int32? bowler_id { get; set; }
        public System.String bowler_name { get; set; }
        public System.String gender { get; set; }
        public System.Int32? i_sgame { get; set; }
        public System.Int32? i_hgame { get; set; }
        public System.Int32? i_sseries { get; set; }
        public System.Int32? i_hseries { get; set; }
        public System.Int32? i_spinfall { get; set; }
        public System.Int32? i_hpinfall { get; set; }
        public System.Int32? max_handicap { get; set; }
        public System.Int32? min_handicap { get; set; }
        public System.Int32? avg_handicap { get; set; }
        public System.Int32? g200 { get; set; }
        public System.Int32? g175 { get; set; }
        public System.Int32? g150 { get; set; }
        public System.Int32? g100 { get; set; }
        public System.Int32? bonuses { get; set; }
        public System.Int32? attendance { get; set; }
        public System.Int32? team_id { get; set; }
        public System.String team_name { get; set; }
        public System.Int32? t_sgame { get; set; }
        public System.Int32? t_hgame { get; set; }
        public System.Int32? t_sseries { get; set; }
        public System.Int32? t_hseries { get; set; }
    }

}
// </auto-generated>
