// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    public interface IMyDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Average> Averages { get; set; } // hba_averages
        System.Data.Entity.DbSet<Bowler> Bowlers { get; set; } // hba_bowler
        System.Data.Entity.DbSet<Bowlernote> Bowlernotes { get; set; } // hba_bowler_note
        System.Data.Entity.DbSet<Draw> Draws { get; set; } // hba_draw
        System.Data.Entity.DbSet<Scoresheet> Scoresheets { get; set; } // hba_score_sheet
        System.Data.Entity.DbSet<Team> Teams { get; set; } // hba_team
        System.Data.Entity.DbSet<Teamnote> Teamnotes { get; set; } // hba_team_note
        System.Data.Entity.DbSet<Vdraw> Vdraws { get; set; } // hba_v_draw
        System.Data.Entity.DbSet<Vindividualgame> Vindividualgames { get; set; } // hba_v_individual_game
        System.Data.Entity.DbSet<VRollingAverage> VRollingAverages { get; set; } // hba_v_RollingAverage
        System.Data.Entity.DbSet<Vweek> Vweeks { get; set; } // hba_v_week
        System.Data.Entity.DbSet<Week> Weeks { get; set; } // hba_week

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        
        // Stored Procedures
        System.Collections.Generic.List<HbaSAveragesAuditReturnModel> HbaSAveragesAudit(int? pWeekId);
        System.Collections.Generic.List<HbaSAveragesAuditReturnModel> HbaSAveragesAudit(int? pWeekId, out int procResult);
        int HbaSEoyCertificate(int? pSeason);
        System.Collections.Generic.List<HbaSRoundWeekIdsReturnModel> HbaSRoundWeekIds(int? pWeekId);
        System.Collections.Generic.List<HbaSRoundWeekIdsReturnModel> HbaSRoundWeekIds(int? pWeekId, out int procResult);
        System.Collections.Generic.List<HbaSSeasonAttendanceReturnModel> HbaSSeasonAttendance(int? pSeason);
        System.Collections.Generic.List<HbaSSeasonAttendanceReturnModel> HbaSSeasonAttendance(int? pSeason, out int procResult);
    }

}
// </auto-generated>
