// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_score_sheet
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Scoresheet: Entity<int>
    {
        public int Id { get; set; } // id (Primary key)
        public int BowlerId { get; set; } // bowler_id
        public int DrawId { get; set; } // draw_id
        public string BlindScore { get; set; } // blind_score (length: 1)
        public int Handicap { get; set; } // handicap
        public int Game1 { get; set; } // game_1
        public int Game2 { get; set; } // game_2
        public int Game3 { get; set; } // game_3

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Average> Averages { get; set; } // hba_averages.hba_averages_fk1

        // Foreign keys
        public virtual Bowler Bowler { get; set; } // hba_score_sheet_fk1
        public virtual Draw Draw { get; set; } // hba_score_sheet_fk2
        
        public Scoresheet()
        {
            Averages = new System.Collections.Generic.List<Average>();
        }
    }

}
// </auto-generated>
