// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_v_draw
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Vdraw: Entity<int>
    {
        public int Season { get; set; } // season
        public int Round { get; set; } // round
        public int? RoundWeek { get; set; } // round_week
        public int Lane { get; set; } // lane
        public string TeamName { get; set; } // team_name (length: 30)
        public int Game1 { get; set; } // game_1
        public int Game2 { get; set; } // game_2
        public int Game3 { get; set; } // game_3
        public int Series { get; set; } // series
        public int Bonus { get; set; } // bonus
        public int Total { get; set; } // total
        public string LegalLineup { get; set; } // legal_lineup (length: 1)
        public int WeekId { get; set; } // week_id
        public int Id { get; set; } // id
        public int TeamId { get; set; } // team_id
    }

}
// </auto-generated>
