// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_v_draw
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Vdraw: Entity<int>
    {
        public int Season { get; set; } // season
        public System.DateTime? WeekDate { get; set; } // week_date
        public int DrawId { get; set; } // draw_id
        public int WeekId { get; set; } // week_id
        public int TeamId { get; set; } // team_id
        public string TeamName { get; set; } // team_name (length: 30)
        public int Lane { get; set; } // lane
        public int Pairing { get; set; } // pairing
        public int TeamGame1 { get; set; } // team_game_1
        public int TeamGame2 { get; set; } // team_game_2
        public int TeamGame3 { get; set; } // team_game_3
        public int Series { get; set; } // series
        public int Bonus { get; set; } // bonus
        public int Total { get; set; } // total
        public string LegalLineup { get; set; } // legal_lineup (length: 1)
        public int ScoresheetId { get; set; } // scoresheet_id
        public int BowlerId { get; set; } // bowler_id
        public int Position { get; set; } // position
        public string BowlerName { get; set; } // bowler_name (length: 30)
        public int Handicap { get; set; } // handicap
        public string BlindScore { get; set; } // blind_score (length: 1)
        public int Game1 { get; set; } // game_1
        public int Game2 { get; set; } // game_2
        public int Game3 { get; set; } // game_3
    }

}
// </auto-generated>
