// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_v_draw
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class VdrawConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Vdraw>
    {
        public VdrawConfiguration()
            : this("dbo")
        {
        }
 
        public VdrawConfiguration(string schema)
        {
            ToTable(schema + ".hba_v_draw");
            HasKey(x => new { x.Season, x.DrawId, x.WeekId, x.TeamId, x.TeamName, x.Lane, x.Pairing, x.TeamGame1, x.TeamGame2, x.TeamGame3, x.Series, x.Bonus, x.Total, x.ScoresheetId, x.BowlerId, x.Position, x.BowlerName, x.Handicap, x.BlindScore, x.Game1, x.Game2, x.Game3 });

            Property(x => x.Season).HasColumnName("season").IsRequired().HasColumnType("int");
            Property(x => x.WeekDate).HasColumnName("week_date").IsOptional().HasColumnType("date");
            Property(x => x.DrawId).HasColumnName("draw_id").IsRequired().HasColumnType("int");
            Property(x => x.WeekId).HasColumnName("week_id").IsRequired().HasColumnType("int");
            Property(x => x.TeamId).HasColumnName("team_id").IsRequired().HasColumnType("int");
            Property(x => x.TeamName).HasColumnName("team_name").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(30);
            Property(x => x.Lane).HasColumnName("lane").IsRequired().HasColumnType("int");
            Property(x => x.Pairing).HasColumnName("pairing").IsRequired().HasColumnType("int");
            Property(x => x.TeamGame1).HasColumnName("team_game_1").IsRequired().HasColumnType("int");
            Property(x => x.TeamGame2).HasColumnName("team_game_2").IsRequired().HasColumnType("int");
            Property(x => x.TeamGame3).HasColumnName("team_game_3").IsRequired().HasColumnType("int");
            Property(x => x.Series).HasColumnName("series").IsRequired().HasColumnType("int");
            Property(x => x.Bonus).HasColumnName("bonus").IsRequired().HasColumnType("int");
            Property(x => x.Total).HasColumnName("total").IsRequired().HasColumnType("int");
            Property(x => x.LegalLineup).HasColumnName("legal_lineup").IsOptional().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(1);
            Property(x => x.ScoresheetId).HasColumnName("scoresheet_id").IsRequired().HasColumnType("int");
            Property(x => x.BowlerId).HasColumnName("bowler_id").IsRequired().HasColumnType("int");
            Property(x => x.Position).HasColumnName("position").IsRequired().HasColumnType("int");
            Property(x => x.BowlerName).HasColumnName("bowler_name").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(30);
            Property(x => x.Handicap).HasColumnName("handicap").IsRequired().HasColumnType("int");
            Property(x => x.BlindScore).HasColumnName("blind_score").IsRequired().IsFixedLength().IsUnicode(false).HasColumnType("char").HasMaxLength(1);
            Property(x => x.Game1).HasColumnName("game_1").IsRequired().HasColumnType("int");
            Property(x => x.Game2).HasColumnName("game_2").IsRequired().HasColumnType("int");
            Property(x => x.Game3).HasColumnName("game_3").IsRequired().HasColumnType("int");
        }
    }

}
// </auto-generated>
