// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_v_individual_game
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Vindividualgame: Entity<int>
    {
        public int Season { get; set; } // season
        public int WeekNumber { get; set; } // week_number
        public int BowlerId { get; set; } // bowler_id
        public int Handicap { get; set; } // handicap
        public int Game { get; set; } // game
        public int Game1 { get; set; } // game_1
        public int DrawId { get; set; } // draw_id
    }

}
// </auto-generated>
