// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_v_week
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Vweek: Entity<int>
    {
        public System.DateTime? WeekDate { get; set; } // week_date
        public int Season { get; set; } // season
        public int WeekNumber { get; set; } // week_number
        public int Round { get; set; } // round
        public int? RoundWeek { get; set; } // round_week
        public int Id { get; set; } // id
    }

}
// </auto-generated>
