// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_v_week
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class VweekConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Vweek>
    {
        public VweekConfiguration()
            : this("dbo")
        {
        }
 
        public VweekConfiguration(string schema)
        {
            ToTable(schema + ".hba_v_week");
            HasKey(x => new { x.Season, x.WeekNumber, x.Round, x.Id });

            Property(x => x.WeekDate).HasColumnName("week_date").IsOptional().HasColumnType("date");
            Property(x => x.Season).HasColumnName("season").IsRequired().HasColumnType("int");
            Property(x => x.WeekNumber).HasColumnName("week_number").IsRequired().HasColumnType("int");
            Property(x => x.Round).HasColumnName("round").IsRequired().HasColumnType("int");
            Property(x => x.RoundWeek).HasColumnName("round_week").IsOptional().HasColumnType("int");
            Property(x => x.Id).HasColumnName("id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
        }
    }

}
// </auto-generated>
