// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_week
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class WeekConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Week>
    {
        public WeekConfiguration()
            : this("dbo")
        {
        }
 
        public WeekConfiguration(string schema)
        {
            ToTable(schema + ".hba_week");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.WeekDate).HasColumnName("week_date").IsRequired().HasColumnType("date");
            Property(x => x.WeekNumber).HasColumnName("week_number").IsRequired().HasColumnType("int");
            Property(x => x.Season).HasColumnName("season").IsRequired().HasColumnType("int");
        }
    }

}
// </auto-generated>
