// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace League.Model
{

    // hba_week
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Week: Entity<int>
    {
        public int Id { get; set; } // id (Primary key)
        public System.DateTime WeekDate { get; set; } // week_date
        public int WeekNumber { get; set; } // week_number
        public int Season { get; set; } // season

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Draw> Draws { get; set; } // hba_draw.hba_draw_fk1
        
        public Week()
        {
            Draws = new System.Collections.Generic.List<Draw>();
        }
    }

}
// </auto-generated>
